### ISSUE TITLE
Always getting "error: Failed to ingest track: Attempted to add track with missing fields."

### ISSUE THREAD

**Issue by connorlandgraf** [jhurliman/node-echoprint-server#6] opened 2013-01-21 09:09 UTC
when attempting to ingest or ingest using the debug, I get the same error. 
I'm inputting all required fields.. any ideas?

**Comment by delcroip** [comment] 2013-04-03 20:07
EDIT: Don't do that ... the source of the issue is the ID type in the database, you need to change the type of all ids for a INT with auto_increment and remove the test on the id length.

It's happend because the id are not filled, I don't know why (should be linked with MySQL). I made a workarround by 

adding the id fields in the SQL request and I fill it with the MySQL command UUID()

modeld/mysql.js
l198 : var sql = 'INSERT INTO artists (name) VALUES (?)';
to:      var sql = 'INSERT INTO artists (name,id) VALUES (?,UUID())';
modeld/mysql.js
l148:  var sql = 'INSERT INTO tracks ' +
l149:    '(name,artist_id,length,import_date) ' +
l150:    'VALUES (?,?,?,?)';
to 
 var sql = 'INSERT INTO tracks ' +
  '(name,artist_id,length,import_date,id) ' +
  'VALUES (?,?,?,?,UUID())';

**Comment by jhurliman** [comment] 2013-04-30 07:28
This should be fixed as of edf0cb8208babd4e8ac9bd258e386995f4baf62c

**Closed as completed by jhurliman** 2013-04-30 07:28 UTC
